### ISSUE TITLE
Coordinate organization outreach efforts

### ISSUE THREAD

**Issue by DuaneOBrien** [foss-responders/about#5]
In order to gather information about who needs help, we should do proactive outreach to organizations like the Python Software Foundation and others.

We need someone to own the process for coordinating what organizations we reach out to, who is reaching out to them, what questions we are asking.

**Comment by DuaneOBrien** [comment]
I have reached out to one (currently unnamed) organization with whom I have a personal relationship. Here is the information I thought was relevant at the time.

How many events are impacted?

What are your current estimated irrecoverable losses due to cancelled events?

If you have to cancel events that are currently planned, what do you estimate your losses would be 6, 3, and 1 month before the events?

I don't know if these are the right questions for everyone, but I wanted to share them as a place to start.

**Comment by Erioldoesdesign** [comment]
I'm going to post a message on the Open Source Africa Discord asking for stories of how folks have been impacted.

I'm going to go with something like this:

"Hi there, I'm looking into gathering how COVID-19/Corona and the subsequent event cancellations, rescheduled and moving online has affected those within the FOSS community. If you're happy to share what the impact has been to you individually or the events that you either run or help organise . This could be a direct financial impact or a less direct financial impact like 'I was hoping to network with possible funders for my OSS project'.

Other than that link I don't really have much in the way of contacts.

Thoughts on my wording? (words aren't my strong skill!)

**Comment by DuaneOBrien** [comment]
Basing off of this list as a guide

https://airtable.com/shrETNURgXNrGWbd8/tblc49hMMykARebo8?blocks=hide
