### ISSUE TITLE
Start aggregating resources for website / discourse

### ISSUE THREAD

**Issue by nuritzi** [foss-responders/about#7]
Since we are still working on the website and discourse set up, I'd like to have an issue dedicated to sharing resources with people so that we don't lose them. 

If you have something you think would benefit our community during this COVID-19 response period, please post it here. 

Relevant issue: [Set up Discourse](https://github.com/foss-responders/fossresponders.com/issues/13)

**Comment by nuritzi** [comment]
## Resources for artists

16-page, living directory of
- tools anyone can use to host virtual shows/meetups/panels
- virtual events that artists and companies are organizing in place of SXSW
- emergency-funding resources for artists

Resource: [Virtual Music Directory](https://docs.google.com/document/d/11wWL_7I4BG76t0V2kw1a4yIeWxUSfGwMQFYdUWAgSnA/preview#heading=h.6p7nn4acptfw)

Source: https://twitter.com/cheriehu42/status/1238571853167431680

**Comment by nuritzi** [comment]
## Pro-bono design resources
 * [Open Source Design](https://discourse.opensourcedesign.net/) - For OSS design contributions you can ask for that here.
 * [Virtual Design Sprint](https://www.virtualdesignsprint.com/) Organises design sprints remotely
 * [Hague Hacks](https://thehaguepeace.org/haguehacks/) - Does in person design thinking for humanitarian crisis and links with OSS projects to make them 'exist'
 * [OpenIDEO](https://www.openideo.com/) - does funded challenges more to do with humanitarian stuff: 
 * [Open Design](https://opendesign.ushahidi.com/ ) - A project to create accessible processes for designers to collaborate and contribute to open source software.

Source: @eriolfox on the Open Collective #crisis-working-group Slack

Note: this list was originally on the [discourse set-up issue](https://github.com/foss-responders/fossresponders.com/issues/13#issuecomment-600795521), but I've moved it here.

**Comment by downeymj** [comment]
I am going to send off a couple referals to experts I know who have volunteered at the [Discourse community call for volunteers](https://meta.discourse.org/t/calling-out-for-volunteer-community-managers/144783) for pandemic related activities. Will be sending them emails and copying @nuritzi today.

Once the website is set up through the Discourse.org hosting free trial, I'll then send an email intro to the Discourse team to ask them about their hosting offer. @nuritzi will send me an email once that's done with the chosen URL so I can point the team to the correct account/site.

**Comment by nuritzi** [comment]
@downeymj I'll reference your update in the issue about setting up the Discourse instance ([Issue #13](https://github.com/foss-responders/fossresponders.com/issues/13)). This one is meant to capture resources that we want to add to Discourse once it's up. Sorry for the confusion!

**Adding some more resources from people on Slack:** 

 * [Meals of Gratitude Collective](https://opencollective.com/mealsofgratitude)
 * [Hosting troll-free/playful zoom calls](https://docs.google.com/document/d/1KLRrnm6g5YvD8QRSPwwNWq6NPk9FYvMpZPy_XEyOmMM/edit)

**Comment by gusaus** [comment]
[Biotechnology Innovation Organization (BIO)](https://www.bio.org/) created the [Coronavirus Hub](https://hub.bio.org/) to connect companies with capacity and resources with those that need them. This new hub will enable users to post requests for urgently needed items and announce the availability of supplies and capacity.

In addition to the website, the open-source platform [Open Social](https://www.getopensocial.com/) might be a valuable resource for other groups looking to connect companies with capacity and resources with those that need them. 

More info on both can be found here -  https://www.getopensocial.com/blog/news-room/bio-uses-open-social-expedite-coronavirus-rd

**Comment by tobiaseigen** [comment]
Hi all! Thanks, @downeymj for connecting me with this initiative. @nuritzi  and I had a call this afternoon and I will be helping set up the new discourse site. I dumped in the resources suggested above as wiki topics in the resources category: https://community.fossresponders.com/c/resources/8 

This was a quick and dirty job, so I am expecting and hoping that you will improve and expand on them them as you see fit once you sign up, including adding any crediting of sources. Thanks!

**Comment by nuritzi** [comment]
Thank you so much for doing that @tobiaseigen!! 

I'll close this issue since we now have a place to add resources.
