### ISSUE TITLE
Create private repo to manage application requests

### ISSUE THREAD

**Issue by rachellawson** [foss-responders/about#9]
The application requests need to be managed within the smaller Application and Oversight teams. To ensure that the teams can see the progress of each application, we will create a private repo where an issue is created for each request. 
The ID of this issue becomes the Unique ID for each application and must be quoted in all future correspondence between fossreposnders and the applicant.
We will create a Kanban board to monitor progress and a series of issue tags to show which applications have been awarded etc

**Comment by DuaneOBrien** [comment]
We'll need to tag @RichardLitt in for this one, I don't have sufficient rights.

**Comment by RichardLitt** [comment]
We'd have to upgrade to paid. I'll email Devon Zeugel and see if we can get private repositories for free. If not, I'm happy to submit expenses to FOSS Responders.

**Comment by RichardLitt** [comment]
@rachellawson Added you as a team member for now. @DuaneOBrien You're now an owner, too.

**Comment by DuaneOBrien** [comment]
@RichardLitt if Devon can't set us up with Teams for free, let me know and I'll pay out of pocket to upgrade is today while we sort it out.

**Comment by RichardLitt** [comment]
This was done! Good work, all.
